version: '3.9'
services:
  postgres:
    image: postgres
    ports:
      - '5434:5432'
    env_file:
      - .env
    restart: always
    volumes:
      - './postgres:/var/lib/postgresql/data'

volumes:
  postgres:


